sudo: false
language: python
python: "2.7"

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
- openssl aes-256-cbc -K $encrypted_504ed2d281e6_key -iv $encrypted_504ed2d281e6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json

install:
- gcloud config set project test-project-271311
- pip install -r requirements.txt -t lib/

script:
- gcloud -q app deploy app.yaml --promote
