sudo: false
language: python
python: "2.7"

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
- echo "key = '${API_KEY}'" > api_key.py
- echo "${CLIENT_SECRET}" > client-secret.json
- cat api_key.py
- cat client-secret.json
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json

install:
- gcloud config set project test-project-271311
- pip install -r requirements.txt -t lib/

script:
- gcloud -q app deploy app.yaml --promote
