# sudo: false
# language: python
# python: "2.7"
# services:
#   - docker

# cache:
#   directories:
#   - "$HOME/google-cloud-sdk/"

deploy:
  provider: gae
  keyfile: "..."
  project: test-project-271311

# env:
# - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_504ed2d281e6_key -iv $encrypted_504ed2d281e6_iv -in client-secret.json.enc -out client-secret.json -d
# - tar -xzf credentials.tar.gz
# - if [ ! -d ${HOME}/google-cloud-sdk ]; then
#      curl https://sdk.cloud.google.com | bash;
#   fi
# - gcloud auth activate-service-account --key-file client-secret.json

# install:
# - gcloud config set project test-project-271311

# script:
# - gcloud app deploy
